openvinotoolkit/openvino_build_deploy

ai_ref_kits/custom_ai_assistant/README.md

Update README.md ai assistant

---

ai_ref_kits/intelligent_queue_management/README.md

Update README.md intelligent queue

---

ai_ref_kits/meter_reader/README.md

Update README.md smart meter

---

ai_ref_kits/explainable_ai/README.md

Update README.md explainable ai

---

ai_ref_kits/automated_self_checkout/README.md

Update README.md self checkout

---

ai_ref_kits/custom_ai_assistant/README.md
ai_ref_kits/custom_ai_assistant/convert_and_optimize_asr.py
ai_ref_kits/custom_ai_assistant/convert_and_optimize_chat.py

Add ASR and LLM in Chinese to extend the custom AI assistant to support Chinese

Add code and instructions to extend the custom AI assistant to support Chinese

---

workshops/accelerating_inference_with_openvino_and_pytorch/pytorch_to_openvino/pytorch_to_openvino_itdc.ipynb

Remove benchmarking to simplify the sample

Remove benchmarking to simplify the sample

---

demos/README.md
demos/healthcare_assistant_demo/README.md
demos/healthcare_assistant_demo/main.py
demos/healthcare_assistant_demo/requirements.txt

Added new healthcare assistant demo

---

ai_ref_kits/multimodal_ai_visual_generator/download_and_prepare_models.py

llama-3 model was getting downloaded in whisper.cpp folder instead of dnd_models

Fixed directory change

---

ai_ref_kits/README.md

Adding Multimodal AI Visual Generator kit to list, and correcting some links

Update kits README.md

---

ai_ref_kits/multimodal_ai_visual_generator/README.md

update to bring it in line with the template used by the other kits

Update Multimodal AI Visual Generator README.md

---

ai_ref_kits/meter_reader/README.md

Adding description for switching detection and segmentation models from PaddlePaddle to YOLOv8 and Deeplabv3+ and running the application.

Update README.md for meter reader

---

ai_ref_kits/meter_reader/requirements.txt

Update requirements.txt for meter reader

---

ai_ref_kits/conversational_ai_chatbot/app.py
ai_ref_kits/conversational_ai_chatbot/requirements.txt

Fixed PDF parsing issue using PyMuPDF and updated requirements

Requirements and Parsing issue fix

---

ai_ref_kits/conversational_ai_chatbot/app.py
ai_ref_kits/conversational_ai_chatbot/requirements.txt

Updated dependencies for llama-index and related OpenVINO components to ensure compatibility.

Conversational ai chatbot

---

ai_ref_kits/conversational_ai_chatbot/app.py

Added sentence tokenization to synthesize function. Please help review. Thanks!

Update app.py with sentence tokenization

---

ai_ref_kits/conversational_ai_chatbot/README.md

Updated Readme with TTS and Params descriptions

Updated Readme with TTS and Params descriptions

---

ai_ref_kits/conversational_ai_chatbot/convert_and_optimize_chat.py

@AnishaUdayakumar please test if it works correctly. I noticed it makes more mistakes as the model is smaller

Added LLama 3.2 to the AI Chatbot

---

ai_ref_kits/agentic_llm_rag/app.py
ai_ref_kits/agentic_llm_rag/convert_and_optimize_asr.py
ai_ref_kits/agentic_llm_rag/convert_and_optimize_llm.py
ai_ref_kits/agentic_llm_rag/requirements.txt

1. Requirements Upgrade:
Upgraded dependencies including optimum-intel, transformers, and other related packages to ensure compatibility and support for the latest models and features.
2. ASR Convert Script Update:
Updated the ASR conversion script to include support for DistilWhisper v3.
3. LLM Model Script Update:
Enhanced the LLM model conversion script to support Llama 3.2-3B.
Adjusted the script to align with the updated dependency requirements and token authentication for gated model access.
Please double check the requirements upgrade is not breaking other changes.

Update Requirements and Model Scripts

---

demos/hide_your_mess_behind_demo/src/ov-jobs.js
demos/hide_your_mess_behind_demo/src/renderer.js

@Roszczyk Improved performance a lot. Could you verify?

Faster image blurring in Hide Your Mess Demo

---

demos/paint_your_dreams_demo/README.md

add few changes that explain the flow of the application

Update README.md on the paint your dream demo

---

ai_ref_kits/agentic_llm_rag/app.py

- Added @AnishaUdayakumar  implementation for a cart that allows you to add items by quantity
-  Quick fix for llamaindex agent's repetition of the first words of its response

Adding quick bug fixes for agentic AI kit

---

ai_ref_kits/README.md

Replaced AI Insight Agent with RAG link with the correct one -- Catchy Agency

Edge AI Reference Kits

---

ai_ref_kits/meter_reader/README.md

Removed the 203- error and replaced the link -- Catchy Agency

Smart Meter Scanning

---

ai_ref_kits/meter_reader/README.md

Removed "edge" -- Catchy Agency

Smart Meter Scanning 2

---

ai_ref_kits/defect_detection_anomalib/README.md

Updated according to client feedback -- Catchy Agency

Defect Detection Anomalib

---

ai_ref_kits/explainable_ai/README.md

Explainable AI

---

ai_ref_kits/custom_ai_assistant/README.md

Custom AI Assistant

---

ai_ref_kits/multimodal_ai_visual_generator/README.md

Multimodal AI Visual Generator

---

ai_ref_kits/agentic_llm_rag/README.md

AI Insight Agent with RAG

---

ai_ref_kits/automated_self_checkout/README.md

Automated Self-Checkout

---

demos/virtual_ai_assistant_demo/agribot_personality.yaml
demos/virtual_ai_assistant_demo/bartender_personality.yaml
demos/virtual_ai_assistant_demo/culinara_personality.yaml
demos/virtual_ai_assistant_demo/healthcare_personality.yaml
demos/virtual_ai_assistant_demo/tutor_personality.yaml

This PR prevents the user to switch agent's context and get information about unrelated, unethical, illegal topics.

Improve content moderation for virtual ai assistant

---

ai_ref_kits/intelligent_queue_management/README.md

Made changes to copy per client request -- Catchy Agency

Intelligent Queue Management

---

ai_ref_kits/conversational_ai_chatbot/requirements.txt
ai_ref_kits/custom_ai_assistant/convert_and_optimize_chat.py
ai_ref_kits/custom_ai_assistant/requirements.txt
ai_ref_kits/multimodal_ai_visual_generator/requirements.txt
demos/paint_your_dreams_demo/requirements.txt
demos/virtual_ai_assistant_demo/requirements.txt
workshops/accelerating_inference_with_openvino_and_pytorch/torch_compile/requirements.txt

This PR updates the transformers and other dependencies in requirements.txt across all affected files, addressing a security vulnerability related to deserialization

Update transformers and other dependencies versions to address security vulnerability

---

ci_readme.md

Added clear and detailed documentation that explains the setup, configuration, and usage of our CI pipelines, making it easier for new contributors to understand and use them effectively.
Ref #201

Adding Documentation on CI Pipelines

---

demos/paint_your_dreams_demo/README.md
demos/paint_your_dreams_demo/setup/run.bat
demos/paint_your_dreams_demo/setup/run.sh

Add model-select to run scripts

Add model-select to run scripts

---

ai_ref_kits/agentic_llm_rag/README.md

- Added link to the Medium article

docs: include medium article to AI agent RAG kit

---

.github/reusable-steps/gradio-action/action.yml
demos/paint_your_dreams_demo/main.py
demos/virtual_ai_assistant_demo/main.py

Fix Windows CI, PowerShell syntax and stdout readiness for Gradio apps

Fix Windows CI, PowerShell syntax and stdout readiness for Gradio apps

---

ai_ref_kits/conversational_ai_chatbot/app.py
ai_ref_kits/conversational_ai_chatbot/requirements.txt

This PR simplifies the conversational AI chatbot implementation by replacing the explicit use of the FAISS vector database with LlamaIndex's default in-memory vector store and also updates on requirements.txt

Feature/replace faiss with llamaindex default vector database 

---

workshops/MSBuild2025/yolo/install.bat

Update install.bat to use 2025.2

---

demos/people_counter_demo/main.py

Update main.py with new Ultralytics integration with OpenVINO for people counter demo.

Update main.py for people counter demo

---

ai_ref_kits/multimodal_ai_visual_generator/README.md

Added the pre-optimized models to simplify the installation

Update README.md for the storyteller

---

ai_ref_kits/agentic_llm_rag/app.py

Removed nest asyncio
